#!/bin/bash
# init script for the openQRM sshterm plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2010, Matthias Rechenburg <matt@openqrm.com>
#
OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/sshterm/include/openqrm-plugin-sshterm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/sshterm/etc/openqrm-plugin-sshterm.conf
# for the post-event to work
openqrm_server_get_config
OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
resource_id=0
resource_openqrmserver=$OPENQRM_SERVER_IP_ADDRESS
# which screen binary to use
if [ -x /usr/bin/screen.real ]; then
	RUNSCREEN="/usr/bin/screen.real"
else
	RUNSCREEN=`which screen`
fi


function openqrm_plugin_sshterm_start() {
	echo "Starting the openQRM sshterm-plugin"
	local CURRENTDIR=`pwd`
	openqrm_plugin_sshterm_stop 1>/dev/null 2>&1
	# generate cert
	cd $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/sshterm/webshell/

	if [ ! -f /root/.webshell/webshell.pem ]; then
		umask 077
		mkdir -p /root/.webshell/
		openssl req  -config "make_certificate.cfg" -keyout "/root/.webshell/webshell.pem" -newkey rsa:1024 -nodes -x509 -days 365 -out "/root/.webshell/webshell.pem"
	fi
	# start the webshell
	SCREEN_NAME=`date +%T%x | sed -e "s/://g" | sed -e "s#/##g"`
	$RUNSCREEN -dmS $SCREEN_NAME ./webshell.py --ssl-cert=/root/.webshell/webshell.pem
	cd $CURRENTDIR
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/sshterm/.running
	return 0
}

function openqrm_plugin_sshterm_stop() {
	echo "Stopping the openQRM sshterm-plugin"
	WEBSHELL_PID=`ps ax | grep webshell.py | grep -v grep | awk {' print $1 '}`
	for PID in $WEBSHELL_PID; do
		kill $PID
	done
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/sshterm/.running
	return 0
}


function openqrm_plugin_sshterm_init() {
	echo "Initializing the openQRM sshterm-plugin"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/sshterm/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/sshterm
	# link the boot-service
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/sshterm/web/boot-service-sshterm.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-sshterm.tgz
	return 0
}


function openqrm_plugin_sshterm_uninstall() {
	echo "Uninstalling the openQRM sshterm-plugin"
	openqrm_plugin_sshterm_stop
	# remove bootservice
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-sshterm.tgz
	# unlinking the web dir
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/sshterm
}


case "$1" in
	start)
		openqrm_plugin_sshterm_start
		;;
	stop)
		openqrm_plugin_sshterm_stop
		;;
	restart)
		openqrm_plugin_sshterm_stop
		sleep 1
		openqrm_plugin_sshterm_start
		;;
	init)
		openqrm_plugin_sshterm_init
		;;
	uninstall)
		openqrm_plugin_sshterm_uninstall
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall|createcert}"
		exit 1

esac
exit $?


